# Generated by Django 6.0.5 on 2026-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IESys_', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iesys',
            old_name='category',
            new_name='expenditure',
        ),
        migrations.AddField(
            model_name='iesys',
            name='income',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
