# Generated by Django 6.0.5 on 2026-05-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IESys_', '0002_rename_category_iesys_expenditure_iesys_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iesys',
            name='expenditure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iesys',
            name='income',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
