# Generated by Django 6.0.5 on 2026-05-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IESys_', '0003_alter_iesys_expenditure_alter_iesys_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iesys',
            old_name='amount',
            new_name='expenditure_amount',
        ),
        migrations.AddField(
            model_name='iesys',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
