# Generated by Django 6.0.5 on 2026-05-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IESys_', '0004_rename_amount_iesys_expenditure_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iesys',
            name='expenditure_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='iesys',
            name='income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
