# Generated by Django 6.0.5 on 2026-05-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IESys_', '0005_alter_iesys_expenditure_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iesys',
            name='expenditure_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='iesys',
            name='income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
