# Generated by Django 6.0.5 on 2026-05-31 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IESys_', '0006_alter_iesys_expenditure_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iesys',
            name='expenditure_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, '支出不能为负数')]),
        ),
        migrations.AlterField(
            model_name='iesys',
            name='income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, '收入不能为负数')]),
        ),
    ]
