# Generated by Django 6.0.5 on 2026-05-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IESys_', '0007_alter_iesys_expenditure_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iesys',
            name='date',
            field=models.DateField(),
        ),
    ]
