# Generated by Django 6.0.5 on 2026-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IESys_', '0008_alter_iesys_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iesys',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
