# Generated by Django 6.0.5 on 2026-05-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IESys_', '0009_alter_iesys_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iesys',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
